### ISSUE TITLE
package -f dir should assume files 'dir/**/*'

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/bosh-gen#105]
If there is a folder `src/gopath/src/extra/...` and the command run is:

```
bosh-gen package myapp -f gopath
```

Then the generated `packages/myapp/spec` should be:

```yaml
name: myapp
files:
- gopath/**/*
```
